import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid,
  BarChart, Bar, ReferenceLine,
} from "recharts";
import results from "../../quant/results/dashboard.json";
import { EDGE_STATS } from "@/lib/edgeStats";

// Phase 25 — the quantitative dashboard.
//
// Everything here is read from quant/results/, generated by the backtest
// pipeline. Nothing is computed in the browser, so the page cannot disagree with
// the research it is reporting. Losing configurations are shown alongside the
// winning ones; nothing is filtered out for looking bad.

const fmt = (v, d = 2) => (v == null || !Number.isFinite(v) ? "—" : v.toFixed(d));
const pct = (v) => (v == null || !Number.isFinite(v) ? "—" : `${v.toFixed(1)}%`);
const rr = (v) => (v == null || !Number.isFinite(v) ? "—" : `${v >= 0 ? "+" : ""}${v.toFixed(3)}R`);
const money = (v) => (v == null || !Number.isFinite(v) ? "—" : `${v >= 0 ? "+" : "-"}€${Math.abs(v).toFixed(0)}`);

const VERDICT_STYLE = {
  "PROVEN EDGE": "border-emerald-500/60 bg-emerald-500/10 text-emerald-300",
  "POSSIBLE EDGE": "border-sky-500/60 bg-sky-500/10 text-sky-300",
  OVERFIT: "border-amber-500/60 bg-amber-500/10 text-amber-300",
  "NO EDGE": "border-red-500/60 bg-red-500/10 text-red-300",
};

const STRATEGY_LABELS = {
  "baseline-long-only": "GoldIntel · long side only",
  "production-baseline": "GoldIntel as shipped (both directions)",
  "setups-long-only": "The four long setups",
  "setup-C-only": "Setup C · bullish pullback",
  "production-scalp": "GoldIntel scalp tier (disabled)",
  "control-random-100pct-long": "Control · 100% long random entry",
  "control-random-5050": "Control · 50/50 random entry",
  "control-long-when-d1-bullish": "Control · long when the daily trend is up",
  "control-ema-cross": "Control · EMA 20/50 cross",
};

const DECAY_STYLE = {
  EDGE_DECAY: "border-red-500/60 bg-red-500/10 text-red-300",
  WATCH: "border-amber-500/60 bg-amber-500/10 text-amber-300",
  IN_LINE: "border-emerald-500/60 bg-emerald-500/10 text-emerald-300",
  UNKNOWN: "border-[#2a3348] text-slate-400",
};

export default function BacktestDashboard() {
  const [selected, setSelected] = useState(results.primary);
  const overview = results.overview ?? {};
  const equity = results.equity?.[selected] ?? [];
  const histogram = results.histogram?.[selected] ?? [];

  const equityData = useMemo(
    () => equity.map((p, i) => ({
      i, cumR: p.cumR, equity: p.equity, drawdown: -p.drawdown,
      date: new Date(p.time).toISOString().slice(0, 10),
    })),
    [equity]
  );

  const monthly = useMemo(
    () => Object.entries(results.monthly ?? {})
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([month, m]) => ({ month, ...m })),
    []
  );

  return (
    <div className="min-h-screen bg-[#070a10] text-slate-200">
      <div className="flex items-center justify-between border-b border-[#1c2230] bg-[#0b0f17] px-4 py-2.5">
        <span className="font-mono text-sm font-semibold tracking-widest text-amber-400">
          XAU/USD · BACKTEST REPORT
        </span>
        <Link to="/" className="font-mono text-[11px] uppercase tracking-wider text-slate-400 hover:text-amber-400">
          ← Live terminal
        </Link>
      </div>

      <div className="mx-auto max-w-[1400px] space-y-3 p-3 lg:p-4">
        {/* Verdict */}
        <div className={`border px-5 py-4 ${VERDICT_STYLE[results.verdict] ?? "border-[#2a3348]"}`}>
          <div className="font-mono text-[10px] uppercase tracking-widest opacity-70">
            Final verdict · {STRATEGY_LABELS[results.primary] ?? results.primary}
          </div>
          <div className="mt-1 font-mono text-2xl font-bold tracking-wider">{results.verdict ?? "—"}</div>
          <div className="mt-2 grid gap-1 font-mono text-[11px] opacity-80 sm:grid-cols-3">
            <span>Development: {results.periods?.development}</span>
            <span>Validation: {results.periods?.validation}</span>
            <span>Final test: {results.periods?.finalTest}</span>
          </div>
          <div className="mt-3 max-w-4xl text-xs leading-relaxed opacity-90">
            Out of sample the primary configuration returns {rr(EDGE_STATS.measured?.strategies?.BASELINE_SWING_LONG_ONLY?.outOfSample?.expectancy)} per
            trade with a profit factor of {fmt(EDGE_STATS.measured?.strategies?.BASELINE_SWING_LONG_ONLY?.outOfSample?.profitFactor)}. The evidence is
            era-specific: {pct(results.walkForward?.byFeed?.legacy?.consistency * 100)} of quarters are profitable in the 2012–2019 era against{" "}
            {pct(results.walkForward?.byFeed?.modern?.consistency * 100)} in the 2020–2025 era. Every figure on this page carries a feed-uncertainty
            band of about ±{EDGE_STATS.feedUncertaintyR}R — the amount a second independent data vendor moves the same measurement.
          </div>
        </div>

        {/* Edge decay */}
        {results.edgeDecay && (
          <div className={`border px-5 py-3 ${DECAY_STYLE[results.edgeDecay.status] ?? "border-[#2a3348]"}`}>
            <div className="font-mono text-[10px] uppercase tracking-widest opacity-70">Edge decay · most recent unseen year</div>
            <div className="mt-1 font-mono text-lg font-bold tracking-wider">{results.edgeDecay.status.replace(/_/g, " ")}</div>
            <div className="mt-1 font-mono text-[11px] opacity-90">
              {results.edgeDecay.latestYear}: {results.edgeDecay.latest?.trades} trades, {rr(results.edgeDecay.latest?.expectancy)},
              profit factor {fmt(results.edgeDecay.latest?.profitFactor)} — against a pooled out-of-sample{" "}
              {rr(results.edgeDecay.pooledOutOfSample?.expectancy)} (z = {fmt(results.edgeDecay.zScore)}).
            </div>
          </div>
        )}

        {/* Verdict criteria */}
        <Panel title="How the verdict was reached">
          <div className="divide-y divide-[#1c2230]">
            {(results.verdicts?.[results.primary]?.checks ?? []).map((c) => (
              <div key={c.name} className="flex flex-wrap items-center gap-x-3 px-4 py-1.5 font-mono text-[11px]">
                <span className={c.pass ? "text-emerald-400" : "text-red-400"}>{c.pass ? "PASS" : "FAIL"}</span>
                <span className="flex-1 text-slate-300">{c.name}</span>
                <span className="text-slate-400">{String(c.actual)}</span>
                <span className="text-slate-600">required {c.required}</span>
              </div>
            ))}
          </div>
        </Panel>

        {/* Strategy comparison — Phase 26 */}
        <Panel title="Final test · every configuration, including the controls">
          <Table
            head={["Configuration", "Trades", "Win rate", "Expectancy", "Profit factor", "Net R", "Net P/L", "Max DD", "Sharpe"]}
            rows={Object.entries(overview).map(([k, m]) => [
              <button
                key={k}
                onClick={() => setSelected(k)}
                className={`text-left hover:text-amber-400 ${k === selected ? "text-amber-400" : "text-slate-200"}`}
              >
                {STRATEGY_LABELS[k] ?? k}
              </button>,
              m.trades, pct(m.winRate), rr(m.expectancy), fmt(m.profitFactor),
              fmt(m.netR, 1), money(m.netPnl), `${fmt(m.maxDrawdownR, 1)}R`, fmt(m.sharpe),
            ])}
            highlight={(row, i) => Object.values(overview)[i]?.expectancy > 0}
          />
        </Panel>

        {/* Across periods */}
        <Panel title="Same configuration, three periods — where the story changes">
          <Table
            head={["Configuration", "Period", "Trades", "Win rate", "Expectancy", "Profit factor", "Max DD"]}
            rows={Object.entries(results.acrossPeriods ?? {}).flatMap(([k, periods]) =>
              Object.entries(periods).map(([p, m], idx) => [
                idx === 0 ? (STRATEGY_LABELS[k] ?? k) : "",
                p, m.trades, pct(m.winRate), rr(m.expectancy), fmt(m.profitFactor), `${fmt(m.maxDrawdownR, 1)}R`,
              ])
            )}
          />
        </Panel>

        <div className="grid gap-3 lg:grid-cols-2">
          {/* Equity curve */}
          <Panel title={`Equity curve · ${STRATEGY_LABELS[selected] ?? selected} · final test`}>
            <div className="h-64 px-2 py-3">
              {equityData.length === 0 ? (
                <Empty>No trades in this period.</Empty>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={equityData}>
                    <CartesianGrid stroke="#1c2230" strokeDasharray="3 3" />
                    <XAxis dataKey="date" tick={{ fill: "#64748b", fontSize: 10 }} minTickGap={40} />
                    <YAxis tick={{ fill: "#64748b", fontSize: 10 }} width={45} />
                    <Tooltip contentStyle={TOOLTIP} labelStyle={{ color: "#94a3b8" }} />
                    <ReferenceLine y={0} stroke="#334155" />
                    <Line type="monotone" dataKey="cumR" name="Cumulative R" stroke="#fbbf24" dot={false} strokeWidth={1.5} />
                    <Line type="monotone" dataKey="drawdown" name="Drawdown (R)" stroke="#ef4444" dot={false} strokeWidth={1} />
                  </LineChart>
                </ResponsiveContainer>
              )}
            </div>
          </Panel>

          {/* R distribution */}
          <Panel title="Distribution of trade outcomes (R)">
            <div className="h-64 px-2 py-3">
              {histogram.length === 0 ? (
                <Empty>No trades in this period.</Empty>
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={histogram.map((b) => ({ bin: b.from.toFixed(2), count: b.count, from: b.from }))}>
                    <CartesianGrid stroke="#1c2230" strokeDasharray="3 3" />
                    <XAxis dataKey="bin" tick={{ fill: "#64748b", fontSize: 9 }} minTickGap={20} />
                    <YAxis tick={{ fill: "#64748b", fontSize: 10 }} width={35} />
                    <Tooltip contentStyle={TOOLTIP} labelStyle={{ color: "#94a3b8" }} />
                    <Bar dataKey="count" name="Trades" fill="#38bdf8" />
                  </BarChart>
                </ResponsiveContainer>
              )}
            </div>
          </Panel>
        </div>

        {/* Conditional breakdowns */}
        <div className="grid gap-3 lg:grid-cols-2">
          <Conditional title="By direction — long vs short" data={results.conditional?.byDirection} />
          <Conditional title="By regime" data={results.conditional?.byRegime} />
          <Conditional title="By session" data={results.conditional?.bySession} />
          <Conditional title="By news proximity" data={results.conditional?.byNews} />
        </div>

        {/* Per-setup evidence tiers */}
        <Panel title="Setups · state and tier assigned from out-of-sample statistics only">
          <Table
            head={["Setup", "State", "Tier", "OOS trades", "OOS win rate", "OOS expectancy", "OOS profit factor", "p(edge ≤ 0)"]}
            rows={Object.entries(EDGE_STATS.measured.setups).map(([id, s]) => [
              id,
              s.state === "DISABLED_NEGATIVE_EDGE"
                ? <span key={id} className="text-red-400" title={s.stateReason ?? ""}>QUARANTINED</span>
                : <span key={id} className="text-slate-300">active</span>,
              s.tier, s.outOfSample?.trades ?? 0, pct(s.outOfSample?.winRate),
              rr(s.outOfSample?.expectancy), fmt(s.outOfSample?.profitFactor), fmt(s.outOfSample?.p, 3),
            ])}
            highlight={(row, i) => Object.values(EDGE_STATS.measured.setups)[i]?.outOfSample?.expectancy > 0}
          />
          <div className="border-t border-[#1c2230] px-4 py-2 text-[10px] leading-relaxed text-slate-500">
            A quarantined setup has a large out-of-sample sample, negative expectancy and a profit factor below 1. The live engine will
            not emit it however strong the current evidence looks. It stays here so the decision can be revisited with more data.
          </div>
        </Panel>

        {/* Calibration — does the evidence score mean anything? */}
        {results.calibration && (
          <Panel title="Evidence-score calibration · does a higher score actually pay?">
            <Table
              head={["Score threshold", "Development", "Validation", "Final test"]}
              rows={results.calibration.map((c) => [
                c.threshold,
                `${c.development.trades} trades · ${rr(c.development.expectancy)}`,
                `${c.validation.trades} trades · ${rr(c.validation.expectancy)}`,
                `${c.finalTest.trades} trades · ${rr(c.finalTest.expectancy)}`,
              ])}
            />
            <div className="border-t border-[#1c2230] px-4 py-2 text-[10px] leading-relaxed text-slate-500">
              Expectancy rises with the score in every period and on both data feeds. That is the evidence that the 0–100 number carries
              information — it is still not a probability, and it is still not sufficient on its own to make a setup tradable.
            </div>
          </Panel>
        )}

        {/* Monthly */}
        <Panel title="Monthly · primary configuration on the final test">
          <Table
            head={["Month", "Trades", "Win rate", "Expectancy", "Net R", "Max DD"]}
            rows={monthly.map((m) => [m.month, m.trades, pct(m.winRate), rr(m.expectancy), fmt(m.netR, 1), `${fmt(m.maxDrawdownR, 1)}R`])}
          />
        </Panel>

        {/* Walk-forward and Monte Carlo */}
        <div className="grid gap-3 lg:grid-cols-2">
          <Panel title="Walk-forward validation · quarterly, by era">
            <dl className="grid grid-cols-2 gap-x-4 gap-y-2 px-4 py-3 font-mono text-[11px]">
              <Field label="2012–2019 quarters profitable" value={`${results.walkForward?.byFeed?.legacy?.profitableWindows} of ${results.walkForward?.byFeed?.legacy?.windows}`} />
              <Field label="2012–2019 mean expectancy" value={rr(results.walkForward?.byFeed?.legacy?.meanExpectancy)} />
              <Field label="2020–2025 quarters profitable" value={`${results.walkForward?.byFeed?.modern?.profitableWindows} of ${results.walkForward?.byFeed?.modern?.windows}`} />
              <Field label="2020–2025 mean expectancy" value={rr(results.walkForward?.byFeed?.modern?.meanExpectancy)} />
              <Field label="Combined consistency" value={fmt(results.walkForward?.summary?.consistency, 3)} />
            </dl>
            <div className="border-t border-[#1c2230] px-4 py-2 text-[10px] leading-relaxed text-slate-500">
              This is the single largest caveat on the result: the configuration did not work in the earlier era and does in the recent one.
            </div>
          </Panel>
          <Panel title="Monte Carlo (5,000 bootstrap resamples)">
            <dl className="grid grid-cols-2 gap-x-4 gap-y-2 px-4 py-3 font-mono text-[11px]">
              <Field label="Resamples ending positive" value={pct(EDGE_STATS.monteCarlo?.pctPositive)} />
              <Field label="Probability of a negative year" value={pct(EDGE_STATS.monteCarlo?.probabilityOfNegativeYear)} />
              <Field label="Median drawdown" value={`${fmt(EDGE_STATS.monteCarlo?.medianDrawdownR, 1)}R`} />
            </dl>
          </Panel>
        </div>

        <p className="px-1 pb-6 text-[10px] leading-relaxed text-slate-600">
          Execution assumptions: {EDGE_STATS.execution}. Position size is derived from the stop distance at{" "}
          {EDGE_STATS.risk?.riskPerTradePct}% of a €{EDGE_STATS.risk?.accountSize?.toLocaleString()} account. All figures were
          produced by the scripts in <code className="text-slate-500">quant/scripts/</code> and stored in{" "}
          <code className="text-slate-500">quant/results/</code>; nothing on this page is recomputed in the browser.
          Losing configurations are shown deliberately. Past results, real or simulated, do not predict future returns.
        </p>
      </div>
    </div>
  );
}

const TOOLTIP = { background: "#0b0f17", border: "1px solid #1c2230", fontFamily: "monospace", fontSize: 11 };

function Panel({ title, children }) {
  return (
    <div className="border border-[#1c2230] bg-[#0b0f17]">
      <div className="border-b border-[#1c2230] px-4 py-2 font-mono text-[11px] uppercase tracking-widest text-slate-400">
        {title}
      </div>
      {children}
    </div>
  );
}

function Field({ label, value }) {
  return (
    <>
      <dt className="text-slate-500">{label}</dt>
      <dd className="text-right text-slate-200">{value ?? "—"}</dd>
    </>
  );
}

function Empty({ children }) {
  return <div className="flex h-full items-center justify-center text-xs text-slate-600">{children}</div>;
}

function Table({ head, rows, highlight = null }) {
  if (!rows || rows.length === 0) {
    return <div className="px-4 py-4 text-xs text-slate-600">No data.</div>;
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full font-mono text-[11px]">
        <thead>
          <tr className="border-b border-[#1c2230] text-left text-slate-500">
            {head.map((h) => (
              <th key={h} className="px-3 py-2 font-normal uppercase tracking-wider">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-[#1c2230]">
          {rows.map((row, i) => (
            <tr key={i} className={highlight?.(row, i) ? "text-emerald-300" : "text-slate-300"}>
              {row.map((cell, j) => (
                <td key={j} className="whitespace-nowrap px-3 py-1.5">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Conditional({ title, data }) {
  const rows = Object.entries(data ?? {})
    .filter(([, m]) => m.trades > 0)
    .sort((a, b) => (b[1].expectancy ?? -9) - (a[1].expectancy ?? -9))
    .map(([k, m]) => [k.replace(/_/g, " "), m.trades, pct(m.winRate), rr(m.expectancy), fmt(m.profitFactor)]);
  return (
    <Panel title={title}>
      <Table head={["Group", "Trades", "Win rate", "Expectancy", "Profit factor"]} rows={rows}
        highlight={(row) => row[3]?.startsWith("+")} />
    </Panel>
  );
}
